deb:
  download_dir: './deb'
  kernel: current # Current version of kernel retrieved by $(uname -r)
  list:
    - linux-image-{KERNEL}
    - linux-modules-{KERNEL}
    - linux-modules-extra-{KERNEL}
    - linux-headers-{KERNEL}
    - build-essential
    - exfat-fuse
    - exfat-utils
    - net-tools
    - dkms
    - binutils
    - fakeroot
    - dpkg-dev
    - fakeroot
    - g++
    - g++-9
    - gcc
    - gcc-9
    - make
    - manpages-dev
    - binutils-common
    - binutils-x86-64-linux-gnu
    - libasan5
    - libatomic1
    - libbinutils
    - libc-dev-bin
    - libc6-dev
    - libcrypt-dev
    - libctf-nobfd0
    - libctf0
    - libfakeroot
    - libgcc-9-dev
    - libitm1
    - liblsan0
    - libquadmath0
    - libstdc++-9-dev
    - libtsan0
    - libubsan1
    - linux-libc-dev

drivers:
  download_dir: './drivers'
  list:
    # Asus USB AC56 WiFi dongle.
    - name: rtl8812au.zip
      url: https://codeload.github.com/gordboy/rtl8812au-5.6.4.2/zip/master
      install:
        - cd rtl8812au-5.6.4.2-master
        - sudo make > /dev/null
        - sudo make install

    # Asus USB AC53 Nano WiFi dongle.
    - name: rtl8822bu.zip
      url: https://codeload.github.com/EntropicEffect/rtl8822bu/zip/master
      install:
        - cd rtl8822bu-master
        - sudo make > /dev/null
        - sudo make install

    # xBox One gamepad.
    - name: xpadneo.zip
      url: https://codeload.github.com/atar-axis/xpadneo/zip/master
      install:
        - cd xpadneo-master
        - sudo chmod +rwx install.sh
        - sudo ./install.sh
        - echo 'options bluetooth disable\_ertm=Y' | sudo tee /etc/modprobe.d/bluetooth.conf
